geometryId: 0150d8f6-2e5a-4ed8-b218-bb09d2565f50
inactiveTextureId: b4106d42-2052-4bec-bf5d-8fc4154e06f5
activeTextureId: 6b2d3eab-0d66-42c9-be92-fc0bdad5baf9
awardSoundId: 8635138c-4d94-4ab0-842f-2a5afd8b141e
trophyCollectedText: 'Trophy Collected:'
trophyCollectedTextColour: gold
trophyNameColour: yellow
trophyTaskSummaryColour: gray
